const isGithub = process.env.GITHUB_ACTIONS === "true";

// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  site: isGithub
    ? "https://smartonesda.github.io"
    : "https://html5-guidebook.vercel.app",
  base: isGithub ? "/html-guidebook/" : "/",
  integrations: [
    starlight({
      title: "HTML Guidebook",
      favicon: "/images/light-smartone.png",
      head: [
        {
          tag: "meta",
          attrs: {
            property: "og:image",
            content:
              "https://html5-guidebook.vercel.app/images/cover-learn.png",
          },
        },
        {
          tag: "meta",
          attrs: {
            property: "og:image:width",
            content: "1200",
          },
        },
        {
          tag: "meta",
          attrs: {
            property: "og:image:height",
            content: "630",
          },
        },
        {
          tag: "meta",
          attrs: {
            name: "twitter:image",
            content:
              "https://html5-guidebook.vercel.app/images/cover-learn.png",
          },
        },
      ],
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/smartonesda/guidebook/tree/html",
        },
      ],
      components: {
        Hero: "./src/components/Hero.astro",
      },
      customCss: ["./src/styles/custom.css"],
      sidebar: [
        {
          label: "BAB 0 — Pengenalan",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab0/introduction/" },
            { label: "Selamat Datang", link: "/bab0/selamat-datang/" },
            { label: "Cara Menggunakan Guidebook", link: "/bab0/cara-menggunakan-guidebook/" },
            { label: "Apa itu Web?", link: "/bab0/apa-itu-web/" },
            { label: "Bagaimana Browser Bekerja", link: "/bab0/bagaimana-browser-bekerja/" },
            { label: "HTML, CSS, JavaScript", link: "/bab0/html-css-javascript/" },
            { label: "Mengapa Belajar HTML", link: "/bab0/mengapa-belajar-html/" },
            { label: "Persiapan Software", link: "/bab0/persiapan-software/" },
            { label: "Install VS Code", link: "/bab0/install-vscode/" },
            { label: "File Pertama", link: "/bab0/file-pertama/" },
            { label: "Membuka di Browser", link: "/bab0/membuka-di-browser/" },
            { label: "Mengenal DevTools", link: "/bab0/mengenal-devtools/" },
            { label: "Error Corner", link: "/bab0/error-corner/" },
            { label: "Ringkasan", link: "/bab0/ringkasan/" },
          ],
        },
        {
          label: "BAB 1 — HTML Fundamentals",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab1/introduction/" },
            { label: "Apa itu HTML?", link: "/bab1/apa-itu-html/" },
            { label: "Sejarah HTML", link: "/bab1/sejarah-html/" },
            { label: "HTML5 — Standar Modern", link: "/bab1/html5/" },
            { label: "Browser Rendering", link: "/bab1/browser-rendering/" },
            { label: "Struktur Dokumen HTML", link: "/bab1/struktur-dokumen-html/" },
            { label: "Anatomi Elemen HTML", link: "/bab1/anatomy-element/" },
            { label: "Komentar HTML", link: "/bab1/komentar-html/" },
            { label: "Whitespace & Indentasi", link: "/bab1/whitespace-indentation/" },
            { label: "HTML Validator", link: "/bab1/html-validator/" },
            { label: "Studi Kasus", link: "/bab1/studi-kasus/" },
            { label: "Mini Project", link: "/bab1/mini-project/" },
            { label: "Challenge", link: "/bab1/challenge/" },
            { label: "Error Corner", link: "/bab1/error-corner/" },
            { label: "Ringkasan", link: "/bab1/ringkasan/" },
          ],
        },
        {
          label: "BAB 2 — Teks & Tipografi",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab2/introduction/" },
            { label: "Heading h1–h6", link: "/bab2/heading/" },
            { label: "Paragraf", link: "/bab2/paragraf/" },
            { label: "Line Break & HR", link: "/bab2/line-break-hr/" },
            { label: "Bold, Italic, Underline", link: "/bab2/bold-italic-underline/" },
            { label: "Teks Semantik", link: "/bab2/teks-semantik/" },
            { label: "Blockquote & Kutipan", link: "/bab2/blockquote/" },
            { label: "Pre & Code", link: "/bab2/pre-code/" },
            { label: "Subscript & Superscript", link: "/bab2/subscript-superscript/" },
            { label: "Studi Kasus", link: "/bab2/studi-kasus/" },
            { label: "Mini Project", link: "/bab2/mini-project/" },
            { label: "Challenge", link: "/bab2/challenge/" },
            { label: "Error Corner", link: "/bab2/error-corner/" },
            { label: "Ringkasan", link: "/bab2/ringkasan/" },
          ],
        },
        {
          label: "BAB 3 — Tautan & Navigasi",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab3/introduction/" },
            { label: "Elemen Anchor", link: "/bab3/elemen-anchor/" },
            { label: "URL Relatif vs Absolut", link: "/bab3/url-relatif-absolut/" },
            { label: "Atribut target", link: "/bab3/atribut-target/" },
            { label: "Anchor Internal", link: "/bab3/anchor-internal/" },
            { label: "Link Email & Telepon", link: "/bab3/link-email-telepon/" },
            { label: "Navigasi Website", link: "/bab3/navigasi-website/" },
            { label: "Studi Kasus", link: "/bab3/studi-kasus/" },
            { label: "Mini Project", link: "/bab3/mini-project/" },
            { label: "Challenge", link: "/bab3/challenge/" },
            { label: "Error Corner", link: "/bab3/error-corner/" },
            { label: "Ringkasan", link: "/bab3/ringkasan/" },
          ],
        },
        {
          label: "BAB 4 — Images & Multimedia",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab4/introduction/" },
            { label: "Elemen Gambar img", link: "/bab4/elemen-gambar-img/" },
            { label: "Atribut src & alt", link: "/bab4/atribut-src-alt/" },
            { label: "Dimensi Gambar", link: "/bab4/dimensi-gambar/" },
            { label: "figure & figcaption", link: "/bab4/figure-figcaption/" },
            { label: "Gambar Responsif", link: "/bab4/gambar-responsif/" },
            { label: "Elemen audio & video", link: "/bab4/elemen-audio-video/" },
            { label: "Atribut Kontrol & Autoplay", link: "/bab4/atribut-kontrol-autoplay/" },
            { label: "Elemen iframe", link: "/bab4/elemen-iframe/" },
            { label: "Organisasi File Media", link: "/bab4/organisasi-file-media/" },
            { label: "Studi Kasus", link: "/bab4/studi-kasus/" },
            { label: "Mini Project", link: "/bab4/mini-project/" },
            { label: "Challenge", link: "/bab4/challenge/" },
            { label: "Error Corner", link: "/bab4/error-corner/" },
            { label: "Ringkasan", link: "/bab4/ringkasan/" },
          ],
        },
        {
          label: "BAB 5 — Lists & Tables",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab5/introduction/" },
            { label: "Daftar ul & ol", link: "/bab5/daftar-ul-ol/" },
            { label: "Atribut List & Nested List", link: "/bab5/atribut-list-nested/" },
            { label: "Description List dl", link: "/bab5/description-list-dl/" },
            { label: "Elemen Tabel th td", link: "/bab5/elemen-tabel-th-td/" },
            { label: "Struktur Tabel head body foot", link: "/bab5/struktur-tabel-head-body-foot/" },
            { label: "colspan & rowspan", link: "/bab5/colspan-rowspan/" },
            { label: "Studi Kasus", link: "/bab5/studi-kasus/" },
            { label: "Mini Project", link: "/bab5/mini-project/" },
            { label: "Challenge", link: "/bab5/challenge/" },
            { label: "Error Corner", link: "/bab5/error-corner/" },
            { label: "Ringkasan", link: "/bab5/ringkasan/" },
          ],
        },
        {
          label: "BAB 6 — Forms",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab6/introduction/" },
            { label: "Elemen Form", link: "/bab6/elemen-form/" },
            { label: "Label & Input", link: "/bab6/label-input/" },
            { label: "Tipe-Tipe Input", link: "/bab6/tipe-tipe-input/" },
            { label: "Pilihan Dropdown & Textarea", link: "/bab6/pilihan-dropdown-textarea/" },
            { label: "Validasi Form Bawaan", link: "/bab6/validasi-form-bawaan/" },
            { label: "Studi Kasus", link: "/bab6/studi-kasus/" },
            { label: "Mini Project", link: "/bab6/mini-project/" },
            { label: "Challenge", link: "/bab6/challenge/" },
            { label: "Error Corner", link: "/bab6/error-corner/" },
            { label: "Ringkasan", link: "/bab6/ringkasan/" },
          ],
        },
        {
          label: "BAB 7 — HTML Attributes",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab7/introduction/" },
            { label: "Anatomi Attribute", link: "/bab7/anatomi-attribute/" },
            { label: "Global Attributes", link: "/bab7/global-attributes/" },
            { label: "id vs class vs name vs value", link: "/bab7/attribute-id-class/" },
            { label: "Boolean Attributes", link: "/bab7/boolean-attributes/" },
            { label: "Custom data-*", link: "/bab7/data-attributes/" },
            { label: "ARIA Attributes", link: "/bab7/aria-attributes/" },
            { label: "Studi Kasus", link: "/bab7/studi-kasus/" },
            { label: "Mini Project", link: "/bab7/mini-project/" },
            { label: "Challenge", link: "/bab7/challenge/" },
            { label: "Error Corner", link: "/bab7/error-corner/" },
            { label: "Ringkasan", link: "/bab7/ringkasan/" },
          ],
        },
        {
          label: "BAB 8 — Semantic HTML",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab8/introduction/" },
            { label: "header & nav", link: "/bab8/header-nav/" },
            { label: "main & article", link: "/bab8/main-article/" },
            { label: "section & aside", link: "/bab8/section-aside/" },
            { label: "footer", link: "/bab8/footer/" },
            { label: "div vs Semantic", link: "/bab8/div-vs-semantic/" },
            { label: "Struktur Halaman Nyata", link: "/bab8/struktur-halaman-nyata/" },
            { label: "Studi Kasus", link: "/bab8/studi-kasus/" },
            { label: "Mini Project", link: "/bab8/mini-project/" },
            { label: "Challenge", link: "/bab8/challenge/" },
            { label: "Error Corner", link: "/bab8/error-corner/" },
            { label: "Ringkasan", link: "/bab8/ringkasan/" },
          ],
        },
        {
          label: "BAB 9 — Metadata & SEO",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab9/introduction/" },
            { label: "Apa itu Metadata?", link: "/bab9/apa-itu-metadata/" },
            { label: "Elemen title & charset", link: "/bab9/title-charset/" },
            { label: "Viewport & Responsive", link: "/bab9/viewport/" },
            { label: "Meta Description & Robots", link: "/bab9/meta-description/" },
            { label: "Elemen link & Favicon", link: "/bab9/link-favicon/" },
            { label: "Open Graph & Social", link: "/bab9/open-graph/" },
            { label: "Studi Kasus", link: "/bab9/studi-kasus/" },
            { label: "Mini Project", link: "/bab9/mini-project/" },
            { label: "Challenge", link: "/bab9/challenge/" },
            { label: "Error Corner", link: "/bab9/error-corner/" },
            { label: "Ringkasan", link: "/bab9/ringkasan/" },
          ],
        },
        {
          label: "BAB 10 — Aksesibilitas",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab10/introduction/" },
            { label: "Mengapa Aksesibilitas?", link: "/bab10/mengapa-aksesibilitas/" },
            { label: "WCAG Dasar", link: "/bab10/wcag-dasar/" },
            { label: "Alt Text yang Baik", link: "/bab10/alt-text/" },
            { label: "ARIA Roles", link: "/bab10/aria-roles/" },
            { label: "Keyboard Navigation", link: "/bab10/keyboard-navigation/" },
            { label: "Skip Navigation", link: "/bab10/skip-navigation/" },
            { label: "Studi Kasus", link: "/bab10/studi-kasus/" },
            { label: "Mini Project", link: "/bab10/mini-project/" },
            { label: "Challenge", link: "/bab10/challenge/" },
            { label: "Error Corner", link: "/bab10/error-corner/" },
            { label: "Ringkasan", link: "/bab10/ringkasan/" },
          ],
        },
        {
          label: "BAB 11 — Best Practices",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab11/introduction/" },
            { label: "Clean HTML & Indentasi", link: "/bab11/clean-html/" },
            { label: "Penamaan & Struktur File", link: "/bab11/naming-struktur/" },
            { label: "Validasi W3C & Linting", link: "/bab11/validasi-linting/" },
            { label: "HTML Anti-Patterns", link: "/bab11/html-anti-patterns/" },
            { label: "Performa Dasar HTML", link: "/bab11/html-performance/" },
            { label: "Studi Kasus", link: "/bab11/studi-kasus/" },
            { label: "Mini Project", link: "/bab11/mini-project/" },
            { label: "Challenge", link: "/bab11/challenge/" },
            { label: "Error Corner", link: "/bab11/error-corner/" },
            { label: "Ringkasan", link: "/bab11/ringkasan/" },
          ],
        },
        {
          label: "BAB 12 — Mini Project Collection",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab12/introduction/" },
            { label: "Project 1 — Personal Biodata", link: "/bab12/project-1-biodata/" },
            { label: "Project 2 — School Profile", link: "/bab12/project-2-school-profile/" },
            { label: "Project 3 — Blog Article", link: "/bab12/project-3-blog-article/" },
            { label: "Project 4 — Product Showcase", link: "/bab12/project-4-product-showcase/" },
            { label: "Project 5 — Event Registration", link: "/bab12/project-5-event-registration/" },
            { label: "Everything Comes Together", link: "/bab12/everything-comes-together/" },
            { label: "Rubrik & Self-Review", link: "/bab12/mini-project-rubrik/" },
            { label: "Challenge", link: "/bab12/challenge/" },
            { label: "Error Corner", link: "/bab12/error-corner/" },
            { label: "Ringkasan", link: "/bab12/ringkasan/" },
          ],
        },
        {
          label: "BAB 13 — Final Project",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab13/introduction/" },
            { label: "Pilihan Project Briefs", link: "/bab13/project-briefs/" },
            { label: "Persyaratan & Spesifikasi", link: "/bab13/project-requirements/" },
            { label: "Arsitektur Informasi", link: "/bab13/information-architecture/" },
            { label: "Panduan Alur Kerja", link: "/bab13/workflow-guide/" },
            { label: "Everything Comes Together", link: "/bab13/everything-comes-together/" },
            { label: "Quality Gate & Validasi", link: "/bab13/quality-gate-validation/" },
            { label: "Panduan Presentasi Karya", link: "/bab13/presentation-guide/" },
            { label: "Rubrik Penilaian", link: "/bab13/rubrik-penilaian/" },
            { label: "Error Corner", link: "/bab13/error-corner/" },
            { label: "Ringkasan", link: "/bab13/ringkasan/" },
          ],
        },
        {
          label: "BAB 14 — Challenge Collection",
          collapsed: true,
          items: [
            { label: "Introduction", link: "/bab14/introduction/" },
            { label: "Lab 1 — Syntax & Structure", link: "/bab14/lab-1-syntax-structure/" },
            { label: "Lab 2 — Navigation & Links", link: "/bab14/lab-2-text-links/" },
            { label: "Lab 3 — Multimedia & Tables", link: "/bab14/lab-3-media-tables/" },
            { label: "Lab 4 — Forms & Inputs", link: "/bab14/lab-4-forms-inputs/" },
            { label: "Lab 5 — Attributes & Data", link: "/bab14/lab-5-attributes-data/" },
            { label: "Lab 6 — Semantics & A11y", link: "/bab14/lab-6-semantic-a11y/" },
            { label: "The Ultimate Boss Challenge", link: "/bab14/boss-challenge/" },
            { label: "Everything Can Break", link: "/bab14/everything-you-learned-can-break/" },
            { label: "Error Corner", link: "/bab14/error-corner/" },
            { label: "Ringkasan", link: "/bab14/ringkasan/" },
          ],
        },
        {
          label: "BAB 15 — HTML Handbook",
          collapsed: true,
          items: [
            { label: "Introduction & Quick Start", link: "/bab15/introduction/" },
            { label: "Kamus Elemen HTML", link: "/bab15/elements-reference/" },
            { label: "Kamus Atribut HTML", link: "/bab15/attributes-reference/" },
            { label: "Kamus Input Types", link: "/bab15/input-types-reference/" },
            { label: "HTML Entities & Karakter", link: "/bab15/entities-reference/" },
            { label: "Decision Guide", link: "/bab15/decision-guide/" },
            { label: "A11y & ARIA Reference", link: "/bab15/accessibility-reference/" },
            { label: "SEO & Metadata Reference", link: "/bab15/seo-metadata-reference/" },
            { label: "Elemen Usang (Deprecated)", link: "/bab15/deprecated-elements/" },
            { label: "VS Code Snippets & Tools", link: "/bab15/vscode-snippets/" },
            { label: "Penutup Roadmap", link: "/bab15/ringkasan/" },
          ],
        },
      ],
    }),
  ],
});

